### PR TITLE
add arrowhead attributes to edges

### PR DESCRIPTION
**Pull request by archaeron**
attributes gotten from here:

https://www.graphviz.org/doc/info/attrs.html#k:arrowType

### CODE REVIEW

**Comment by csicar** [comment]
Thanks for contributing that. Looks good to me.

**Comment by archaeron** [comment]
thank you for merging this so quickly!

**Comment by csicar** [comment]
No problem :)
I've also bumped the version: https://pursuit.purescript.org/packages/purescript-dotlang/3.1.0

**Comment by archaeron** [comment]
yes! this was great :) we're already using the new version and it looks great
thanks

**Pull request merged**
